name: go
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - run: |
          GOOS="windows" GOARCH="amd64" go build -o bin/wzky_windows_amd64.exe main.go
          GOOS="linux" GOARCH="amd64" go build -o bin/wzky_linux_amd64 main.go
          GOOS="darwin" GOARCH="amd64" go build -o bin/wzky_darwin_amd64 main.go
